# Site settings
title: ng-recaptcha
description: "Angular component for Google reCAPTCHA"
baseurl: "/ng-recaptcha" # the subpath of your site, e.g. /blog
cacheBusterVer: "3.0.0"
exclude: [
  'Gemfile',
  'Gemfile.lock',
# <DEBUG> Comment next line for debugging session
  'examples/node_modules',
  'examples/package.json',
  'examples/tsconfig.json',
  'examples/tslint.json',
  'examples/ng-lint.json',
]

# SystemJS mapping for ng2-recaptcha component
recaptchaMapping: "https://npmcdn.com/ng-recaptcha@3.0.0" # stick to a particular version to avoid caching confusion
# <DEBUG> Uncomment next line for debugging session
# recaptchaMapping: "./examples/node_modules/ng-recaptcha"

# Build settings
markdown: kramdown
